developers/urls.py
from django.urls import path
from .views import DeveloperListView, DeveloperCreateView, DeveloperDetailView, DeveloperUpdateView, DeveloperDeleteView

app_name = 'developers'

urlpatterns = [
    path('', DeveloperListView.as_view(), name='developer-list'),
    path('create/', DeveloperCreateView.as_view(), name='developer-create'),
    path('<int:pk>/', DeveloperDetailView.as_view(), name='developer-detail'),
    path('<int:pk>/update/', DeveloperUpdateView.as_view(), name='developer-update'),
    path('<int:pk>/delete/', DeveloperDeleteView.as_view(), name='developer-delete'),
]

issue_tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, include
from issues.views import LandingPageView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('issues/', include('issues.urls', namespace="issues")),
    path('developers/', include('developers.urls', namespace="developers")),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

issues/urls.py
from django.urls import path
from .views import IssueListView, IssueDetailView, IssueCreateView, IssueUpdateView, IssueDeleteView, AssignDeveloperView, CategoryListView, CategoryDetailView, IssueCategoryUpdateView

app_name = "issues"

urlpatterns = [
    path('', IssueListView.as_view(), name='issue-list'),
    path('create/', IssueCreateView.as_view(), name='issue-create'),
    path('<int:pk>/', IssueDetailView.as_view(), name='issue-detail'),
    path('<int:pk>/update/', IssueUpdateView.as_view(), name='issue-update'),
    path('<int:pk>/delete/', IssueDeleteView.as_view(), name='issue-delete'),
    path('<int:pk>/assign_developer/', AssignDeveloperView.as_view(), name='assign-developer'),
    path('<int:pk>/category/', IssueCategoryUpdateView.as_view(), name='issue-category-update'),
    path('categories', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail')
]

developers/models.py
from django.db import models

# Create your models here.

developers/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()

class DeveloperModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = {
            'email',
            'username',
            'first_name',
            'last_name'
        }

developers/views.py
import random

from django.core.mail import send_mail
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import reverse
from issues.models import Developer
from .forms import DeveloperModelForm
from .mixins import OwnerAndLoginRequiredMixin

class DeveloperListView(OwnerAndLoginRequiredMixin, generic.ListView):
    template_name = "developers/developer_list.html"

    def get_queryset(self):
        team = self.request.user.userprofile
        return Developer.objects.filter(team=team)

class DeveloperCreateView(OwnerAndLoginRequiredMixin, generic.CreateView):
    template_name = "developers/developer_create.html"
    form_class = DeveloperModelForm

    def get_success_url(self):
        return reverse("developers:developer-list")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_agent = True
        user.is_owner = False
        user.save()
        Developer.objects.create(
            user=user,
            team=self.request.user.userprofile
        )
        send_mail(
            subject="You are invited to be a developer",
            message="Please login to start working with Issue Tracker.",
            from_email="admin@sukhdeep.tech",
            recipient_list=[user.email]
        )
        return super(DeveloperCreateView, self).form_valid(form)

class DeveloperDetailView(OwnerAndLoginRequiredMixin, generic.DetailView):
    template_name = "developers/developer_detail.html"
    context_object_name = "developer"

    def get_queryset(self):
        team = self.request.user.userprofile
        return Developer.objects.filter(team=team)

class DeveloperUpdateView(OwnerAndLoginRequiredMixin, generic.UpdateView):
    template_name = "developers/developer_update.html"
    form_class = DeveloperModelForm

    def get_success_url(self):
        return reverse("developers:developer-list")

    def get_queryset(self):
        team = self.request.user.userprofile
        return Developer.objects.filter(team=team)

class DeveloperDeleteView(OwnerAndLoginRequiredMixin, generic.DeleteView):
    template_name = "developers/developer_delete.html"
    context_object_name = "developer"

    def get_success_url(self):
        return reverse("developers:developer-list")

    def get_queryset(self):
        team = self.request.user.userprofile
        return Developer.objects.filter(team=team)

developers/templates/developers/developer_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
    <div class="max-w-lg mx-auto">

        <div class="py-5 border-b border-gray-200">
            <a class="hover:text-blue-500 mt-3" href="{% url 'developers:developer-list' %}">Go back to developers</a>
        </div>

        <h1 class="text-4xl text-gray-800">Create a new developer</h1>
        <form method="post" class="mt-3">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
        </form>

    </div>
{% endblock content %}

developers/templates/developers/developer_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
    <div class="max-w-lg mx-auto">
        <div class="py-5 border-b border-gray-200">
            <a class="hover:text-blue-500 mt-3" href="{% url 'developers:developer-list' %}">Go back to developers</a>
        </div>

        <h1 class="text-3xl text-gray-800">Do you want to delete this developer?</h1>
        <form method="post" class="mt-5">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
        </form>
    </div>
{% endblock content %}

developers/templates/developers/developer_detail.html
   
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">Developer</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ developer.user.username }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'developers:developer-detail' developer.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'developers:developer-update' developer.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Update Details
                </a>    
            </div>
            <div class="flex border-t border-gray-300 py-2">
                <span class="text-gray-500">Full Name</span>
                <span class="ml-auto text-gray-900">{{ developer.user.first_name }} {{ developer.user.last_name }}</span>
            </div>
            <div class="flex border-t border-gray-300 py-2">
                <span class="text-gray-500">Email</span>
                <span class="ml-auto text-gray-900">{{ developer.user.email }}</span>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

developers/templates/developers/developer_list.html
{% extends 'base.html' %}

{% block content %}
    <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800">Developers</h1>
            </div>
            <div>
                <a class="text-gray-500 hover:text-green-500" href="{% url 'developers:developer-create' %}">Create Developer</a>
            </div>
        </div>
        
        <div class="flex flex-wrap -m-4">
            {% for developer in object_list %}
                <div class="p-4 lg:w-1/2 md:w-full">
                <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                    <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-green-100 text-green-500 flex-shrink-0">
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                        <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                    </svg>
                    </div>
                    <div class="flex-grow">
                    <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{ developer.user.username }}</h2>
                    <a href="{% url 'developers:developer-detail' developer.pk %}" class="mt-3 text-green-500 inline-flex items-center">View this developer
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                        </svg>
                    </a>
                    </div>
                </div>
                </div>
            {% endfor %}
        </div>
        </div>
    </section>

{% endblock content %}

developers/templates/developers/developer_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">Developer</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ developer.user.username }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'developers:developer-detail' developer.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'developers:developer-update' developer.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Update Details
                </a>
            </div>
            <form form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
            </form>
            <div class="mt-5 py-5 border-t border-gray-200">
                <a href="{% url 'developers:developer-delete' developer.pk %}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                    Delete
                </a>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}