issue_tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, include
from issues.views import LandingPageView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('issues/', include('issues.urls', namespace="issues")),
    path('developers/', include('developers.urls', namespace="developers")),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

issues/urls.py
from django.urls import path
from .views import IssueListView, IssueDetailView, IssueCreateView, IssueUpdateView, IssueDeleteView, AssignDeveloperView, CategoryListView, CategoryDetailView, IssueCategoryUpdateView

app_name = "issues"

urlpatterns = [
    path('', IssueListView.as_view(), name='issue-list'),
    path('create/', IssueCreateView.as_view(), name='issue-create'),
    path('<int:pk>/', IssueDetailView.as_view(), name='issue-detail'),
    path('<int:pk>/update/', IssueUpdateView.as_view(), name='issue-update'),
    path('<int:pk>/delete/', IssueDeleteView.as_view(), name='issue-delete'),
    path('<int:pk>/assign_developer/', AssignDeveloperView.as_view(), name='assign-developer'),
    path('<int:pk>/category/', IssueCategoryUpdateView.as_view(), name='issue-category-update'),
    path('categories', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail')
]

issues/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    is_owner = models.BooleanField(default=True)
    is_developer = models.BooleanField(default=False)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Issue(models.Model):
    CATEGORY_CHOICES = (
        ('P1', 'P1'),
        ('P2', 'P2'),
        ('P3', 'P3')
    )

    title = models.CharField(max_length=50)

    resolved = models.BooleanField(default=False)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=100)
    team = models.ForeignKey(UserProfile, on_delete=models.CASCADE) # team in which the developer belongs
    developer = models.ForeignKey("Developer", on_delete=models.SET_NULL, null=True, blank=True)
    category = models.ForeignKey("Category", related_name="issues", on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.title} | {self.developer} | resolved: {self.resolved}"

class Developer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    team = models.ForeignKey(UserProfile, on_delete=models.CASCADE) # team in which the developer belongs

    def __str__(self):
        return self.user.email
        
class Category(models.Model):
    name = models.CharField(max_length=30)
    team = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

def post_user_created_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(post_user_created_signal, sender=User)

issues/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.forms.models import ModelChoiceField
from django.http import request

from .models import Issue, Developer

User = get_user_model()

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',)
        field_classes = {'username': UsernameField}

class IssueModelForm(forms.ModelForm):
    class Meta:
        model = Issue
        fields = (
            'title',
            'category',
            'team',
            'developer'
        )

class AssignDeveloperForm(forms.Form):
    developer = ModelChoiceField(queryset=Developer.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        developers = Developer.objects.filter(team=request.user.userprofile)
        super(AssignDeveloperForm, self).__init__(*args, **kwargs)
        self.fields["developer"].queryset = developers

class IssueCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Issue
        fields = (
            'category',
        )

issues/views.py
from django.db.models.aggregates import Count
from django.shortcuts import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.views import generic
from .models import Issue, Category
from .forms import IssueModelForm, CustomUserCreationForm, AssignDeveloperForm, IssueCategoryUpdateForm
from developers.mixins import OwnerAndLoginRequiredMixin

class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("login")

class LandingPageView(generic.TemplateView):
    template_name = "landing.html"

class IssueListView(LoginRequiredMixin, generic.ListView):
    template_name = "issues/issue_list.html"
    context_object_name = "issues"
    
    def get_queryset(self):
        user = self.request.user

        if user.is_owner:
            queryset = Issue.objects.filter(team=user.userprofile, 
                developer__isnull=False
            )
        else:
            queryset = Issue.objects.filter(team=user.developer.team)
            queryset = queryset.filter(developer__user=self.request.user)

        return queryset

    def get_context_data(self, **kwargs):
        context = super(IssueListView, self).get_context_data(**kwargs)
        user = self.request.user
        
        if user.is_owner:
            queryset = Issue.objects.filter(
                team=user.userprofile,
                developer__isnull=True
            )
            context.update({
                "unassigned_issues": queryset
            })
        return context

class IssueDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "issues/issue_detail.html"
    context_object_name = "issue"

    def get_queryset(self):
        user = self.request.user

        if user.is_owner:
            queryset = Issue.objects.filter(team=user.userprofile)
        else:
            queryset = Issue.objects.filter(team=user.developer.team)
            queryset = queryset.filter(developer__user=self.request.user)

        return queryset

class IssueCreateView(OwnerAndLoginRequiredMixin, generic.CreateView):
    template_name = "issues/issue_create.html"
    form_class = IssueModelForm

    def get_success_url(self):
        return reverse("issues:issue-list")

    def form_valid(self, form):
        send_mail(
            subject="Issue has been created",
            message="Test issue message",
            from_email="test@sukhdeep.tech",
            recipient_list=["test_recipient@sukhdeep.tech"]
        )
        return super(IssueCreateView, self).form_valid(form)

class IssueUpdateView(OwnerAndLoginRequiredMixin, generic.UpdateView):
    template_name = "issues/issue_update.html"
    form_class = IssueModelForm

    def get_queryset(self):
        user = self.request.user
        return Issue.objects.filter(team=user.userprofile)

    def get_success_url(self):
        return reverse("issues:issue-list")

class IssueDeleteView(OwnerAndLoginRequiredMixin, generic.DeleteView):
    template_name = "issues/issue_delete.html"

    def get_queryset(self):
        user = self.request.user
        return Issue.objects.filter(team=user.userprofile)

    def get_success_url(self):
        return reverse("issues:issue-list")

class AssignDeveloperView(OwnerAndLoginRequiredMixin, generic.FormView):
    template_name = "issues/assign_developer.html"
    form_class = AssignDeveloperForm

    def get_form_kwargs(self, **kwargs):
        kwargs = super(AssignDeveloperView, self).get_form_kwargs(**kwargs)
        kwargs.update({
            "request": self.request
        })
        return kwargs

    def get_success_url(self):
        return reverse("issues:issue-list")

    def form_valid(self, form):
        developer = form.cleaned_data["developer"]
        issue = Issue.objects.get(id=self.kwargs["pk"])
        issue.developer = developer
        issue.save()
        return super(AssignDeveloperView, self).form_valid(form)

class CategoryListView(LoginRequiredMixin, generic.ListView):
    template_name = "issues/category_list.html"
    context_object_name = "category_list"

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        user = self.request.user

        if user.is_owner:
            queryset = Issue.objects.filter(team=user.userprofile)
        else:
            queryset = Issue.objects.filter(team=user.developer.team)

        context.update({
            "unassigned_issue_count": queryset.filter(category__isnull=True).count(),
            "inprogress_issue_count": queryset.filter(category__name="InProgress").count(),
            "completed_issue_count": queryset.filter(category__name="Completed").count()
        })

        return context

    def get_queryset(self):
        user = self.request.user

        if user.is_owner:
            queryset = Category.objects.filter(team=user.userprofile)
        else:
            queryset = Category.objects.filter(team=user.developer.team)

        return queryset

class CategoryDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "issues/category_detail.html"
    context_object_name = "category"

    def get_queryset(self):
        user = self.request.user

        if user.is_owner:
            queryset = Category.objects.filter(team=user.userprofile)
        else:
            queryset = Category.objects.filter(team=user.developer.team)

        return queryset

class IssueCategoryUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = "issues/issue_category_update.html"
    form_class = IssueCategoryUpdateForm

    def get_queryset(self):
        user = self.request.user

        if user.is_owner:
            queryset = Issue.objects.filter(team=user.userprofile)
        else:
            queryset = Issue.objects.filter(team=user.developer.team)
            queryset = queryset.filter(developer__user=self.request.user)

        return queryset

    def get_success_url(self):
        return reverse("issues:issue-detail", kwargs={"pk": self.get_object().id})

issues/templates/issues/assign_developer.html
{% extends "base.html" %}

{% block content %}
    <a href="{% url 'issues:issue-list' %}">Go back to issues</a>

    <hr>

    <h1>Assign a developer to this issue</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

issues/templates/issues/category_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">
            {{ category.name }}
        </h1>
        <p class="lg:w-2/3 mx-auto issueing-relaxed text-base">
            These are the issues under this category
        </p>
        <a href="{% url 'issues:category-update' category.pk %}" class="hover:text-blue-500">Update</a>
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200 rounded-tl rounded-bl">
                    Title
                </th>
            </tr>
          </thead>
          <tbody>
            {% for issue in category.issues.all %}
                <tr>
                    <td class="px-4 py-3">
                      <a class="hover:text-blue-500" href="{% url 'issues:issue-detail' issue.pk %}">{{ issue.title }}</a>
                    </td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>

{% endblock content %}

issues/templates/issues/category_list.html
{% extends "base.html" %}

{% block content %}
    <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto">
            <div class="flex flex-col text-center w-full mb-20">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Categories</h1>
            <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
                Categories dividing the issues into separte sections.
            </p>
            </div>
            <div class="lg:w-2/3 w-full mx-auto overflow-auto">
                <table class="table-auto w-full text-left whitespace-no-wrap">
                    <thead>
                    <tr>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Name</th>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Issue Count</th>
                    </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="px-4 py-3">Unassigned</td>
                            <td class="px-4 py-3">{{ unassigned_issue_count }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-3">In Progress</td>
                            <td class="px-4 py-3">{{ inprogress_issue_count }}</td>
                        </tr>
                        <tr>
                            <td class="px-4 py-3">Completed</td>
                            <td class="px-4 py-3">{{ completed_issue_count }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </section>
{% endblock content %}

issues/templates/issues/issue_category_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">Issue</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ issue.title }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'issues:issue-detail' issue.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'issues:issue-category-update' issue.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Category
                </a>
                <a href="{% url 'issues:issue-update' issue.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Update Details
                </a>
            </div>
            <form form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
            </form>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

issues/templates/issues/issue_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
    <div class="max-w-lg mx-auto">
        <a class="hover:text-blue-500" href="{% url 'issues:issue-list' %}">Go back to issues</a>
        <div class="py-5 border-t border-gray-200">
            <h1 class="text-4xl text-gray-800">Create a new issue</h1>
        </div>

        <form method="post" class="mt-5">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
        </form>
    </div>
{% endblock content %}

issues/templates/issues/issue_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
    <div class="max-w-lg mx-auto">
        <div class="py-5 border-b border-gray-200">
            <a class="hover:text-blue-500 mt-3" href="{% url 'issues:issue-list' %}">Go back to issues</a>
        </div>

        <h1 class="text-3xl text-gray-800">Do you want to delete this issue?</h1>
        <form method="post" class="mt-5">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
        </form>
    </div>
{% endblock content %}

issues/templates/issues/issue_detail.html
{% extends "base.html" %}

{% block content %}
    <section class="text-gray-700 body-font overflow-hidden">
        <div class="container px-5 py-24 mx-auto">
            <div class="lg:w-4/5 mx-auto flex flex-wrap">
                <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                    <div class="w-full flex items-center justify-between space-x-6">
                        <div class="flex-1 truncate">
                            <div class="flex items-center space-x-3">
                                <h3 class="text-3xl text-gray-900 font-medium truncate">{{ issue.title }}</h3>
                            </div>
                        </div>
                    </div>
                    <div class="flex mb-4">
                        <a href="{% url 'issues:issue-detail' issue.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                            Overview
                        </a>
                        <a href="{% url 'issues:issue-category-update' issue.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                            Category
                        </a>
                        <a href="{% url 'issues:issue-update' issue.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                            Update Details
                        </a>    
                    </div>
                    <div class="flex border-t border-gray-300 py-2">
                        <span class="text-gray-500">Category</span>
                        <span class="ml-auto text-gray-900">{{ issue.category }}</span>
                    </div>
                    <div class="flex border-t border-gray-300 py-2">
                        <span class="text-gray-500">Developer</span>
                        <span class="ml-auto text-gray-900">{{ issue.developer }}</span>
                    </div>
                    <div class="flex border-t border-b mb-6 border-gray-300 py-2">
                        <span class="text-gray-500">Resolved</span>
                        <span class="ml-auto text-gray-900">{{ issue.resolved }}</span>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
{% endblock content %}

issues/templates/issues/issue_list.html
{% extends "base.html" %}

{% block content %}
    <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800">Issues</h1>
                <a class="text-gray-500 hover:text-blue-500" href="{% url 'issues:category-list' %}">
                    View Categories
                </a>
            </div>
            {% if request.user.is_owner %}
                <div>
                    <a class="text-gray-500 hover:text-green-500" href="{% url 'issues:issue-create' %}">
                        Create Issue
                    </a>
                </div>
            {% endif %}
        </div>
        
        <div class="flex flex-wrap -m-4">
            {% for issue in issues %}
                <div class="p-4 lg:w-1/2 md:w-full">
                    <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                        <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-green-100 text-green-500 flex-shrink-0">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                            <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                        </svg>
                        </div>
                        <div class="flex-grow">
                        <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{ issue.title }}</h2>
                        <a href="{% url 'issues:issue-detail' issue.pk %}" class="mt-3 text-green-500 inline-flex items-center">View this issue
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                            <path d="M5 12h14M12 5l7 7-7 7"></path>
                            </svg>
                        </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% if unassigned_issues.exists %}
            <div class="mt-5 flex flex-wrap -m-4">
                <div class="p-4 w-full">
                    <h1 class="text-4xl text-gray-800">Unassigned issues</h1>
                </div>
                {% for issue in unassigned_issues %}
                    <div class="p-4 lg:w-1/2 md:w-full">
                        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                            <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-green-100 text-green-500 flex-shrink-0">
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                            </svg>
                            </div>
                            <div class="flex-grow">
                            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{ issue.title }}</h2>
                            <a href="{% url 'issues:assign-developer' issue.pk %}" class="mt-3 text-green-500 inline-flex items-center">Assign Developer
                                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                <path d="M5 12h14M12 5l7 7-7 7"></path>
                                </svg>
                            </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        </div>
    </section>
{% endblock content %}

issues/templates/issues/issue_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">Issue</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ issue.title }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'issues:issue-detail' issue.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'issues:issue-category-update' issue.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Category
                </a>
                <a href="{% url 'issues:issue-update' issue.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Update Details
                </a>
            </div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
            </form>
            <div class="mt-5 py-5 border-t border-gray-200">
                <a href="{% url 'issues:issue-delete' issue.pk %}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                    Delete
                </a>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}