developers/urls.py
from django.urls import path
from .views import DeveloperListView, DeveloperCreateView, DeveloperDetailView, DeveloperUpdateView, DeveloperDeleteView

app_name = 'developers'

urlpatterns = [
    path('', DeveloperListView.as_view(), name='developer-list'),
    path('create/', DeveloperCreateView.as_view(), name='developer-create'),
    path('<int:pk>/', DeveloperDetailView.as_view(), name='developer-detail'),
    path('<int:pk>/update/', DeveloperUpdateView.as_view(), name='developer-update'),
    path('<int:pk>/delete/', DeveloperDeleteView.as_view(), name='developer-delete'),
]

issue_tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, include
from issues.views import LandingPageView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('issues/', include('issues.urls', namespace="issues")),
    path('developers/', include('developers.urls', namespace="developers")),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

issues/urls.py
from django.urls import path
from .views import IssueListView, IssueDetailView, IssueCreateView, IssueUpdateView, IssueDeleteView, AssignDeveloperView, CategoryListView, CategoryDetailView, IssueCategoryUpdateView

app_name = "issues"

urlpatterns = [
    path('', IssueListView.as_view(), name='issue-list'),
    path('create/', IssueCreateView.as_view(), name='issue-create'),
    path('<int:pk>/', IssueDetailView.as_view(), name='issue-detail'),
    path('<int:pk>/update/', IssueUpdateView.as_view(), name='issue-update'),
    path('<int:pk>/delete/', IssueDeleteView.as_view(), name='issue-delete'),
    path('<int:pk>/assign_developer/', AssignDeveloperView.as_view(), name='assign-developer'),
    path('<int:pk>/category/', IssueCategoryUpdateView.as_view(), name='issue-category-update'),
    path('categories', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail')
]

templates/base.html
{% load static %}

<html>
    <head>
        <title>Issue Tracker</title>
        <link href="{% static 'css/styles.css' %}" rel="stylesheet">
        <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    </head>
    <body>
        <div class="max-w-7xl mx-auto">
            {% include "navbar.html" %}
            {% block content %}
            {% endblock content %}
        </div>
        {% include "scripts.html" %}
    </body>
</html>

templates/landing.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">Issue Tracker</h1>
        <p class="mb-8 leading-relaxed">The tracker helps you manage on going issues with the project.</p>
      </div>
    </div>
</section>
{% endblock content %}

templates/navbar.html
<header class="text-gray-600 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
      <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
          <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
        </svg>
        <span class="ml-3 text-xl">Issue Tracker</span>
      </a>
      <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
        {% if not request.user.is_authenticated %}
          <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-900">Sign Up</a>
        {% else %}
          {% if request.user.is_owner %}
            <a href="{% url 'developers:developer-list' %}" class="mr-5 hover:text-gray-900">Developers</a>
          {% endif %}
          
          <a href="{% url 'issues:issue-list' %}" class="mr-5 hover:text-gray-900">Issues</a>
        {% endif %}  
      </nav>
      {% if request.user.is_authenticated %}
        Logged in as: {{ request.user.username }}
        <a href="{% url 'logout' %}" class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Logout
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
            <path d="M5 12h14M12 5l7 7-7 7"></path>
          </svg>
        </a>
      {% else %}
        <a href="{% url 'login' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Login
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
            <path d="M5 12h14M12 5l7 7-7 7"></path>
          </svg>
        </a>
      {% endif %}
    </div>
</header>

templates/scripts.html
{% load static %}

<script src="{% static 'js/main.js' %}"></script>

templates/second_page.html
<html>
    <h1>Hello again!</h1>
    <ul>
        {% for issue in issues %}
            <li>{{ issue }}</li>
        {% endfor %}
    </ul>
</html>